import { expect, test } from "@playwright/test";
const platformUrl = process.env.SENTINELLAN_E2E_PLATFORM_URL ?? "http://127.0.0.1:3102";
test("owner provisions a company through the isolated platform portal", async ({page}) => {
  await page.goto(`${platformUrl}/platform/login`);
  await page.getByLabel("Email", {exact:true}).fill("owner@e2e.test");
  await page.getByLabel("Mật khẩu", {exact:true}).fill("Owner-e2e-only-2026-secret!");
  await page.getByRole("button",{name:"Đăng nhập chủ hệ thống"}).click();
  await expect(page.getByRole("heading",{name:"Các công ty đang sử dụng"})).toBeVisible();
  const code = `e2e-${Date.now()}`;
  await page.getByLabel("Mã công ty",{exact:true}).fill(code);
  await page.getByLabel("Tên công ty",{exact:true}).fill(code);
  await page.getByLabel("Email Admin công ty",{exact:true}).fill("admin@e2e-company.test");
  await page.getByLabel("Tên Admin công ty",{exact:true}).fill("Admin công ty thử");
  await page.getByLabel("Lý do cấp tài khoản",{exact:true}).fill("Công ty đã đăng ký sử dụng");
  await page.getByLabel("Tôi xác nhận cấp quyền quản trị cho người này trong công ty vừa tạo.").check();
  await page.getByRole("button",{name:"Tạo công ty và cấp link kích hoạt"}).click();
  await expect(page.getByRole("heading",{name:`Đã tạo công ty ${code}`})).toBeVisible();
  await expect(page.getByRole("row").filter({hasText:code})).toContainText("Chưa có Agent kết nối");
  await expect(page.getByLabel("Link kích hoạt")).toHaveValue(/\/company\/activate#token=/);
  await page.getByRole("row").filter({hasText:code}).getByRole("button",{name:"Tạm ngưng",exact:true}).click();
  await page.getByLabel("Lý do",{exact:true}).fill("Tạm ngưng theo yêu cầu công ty");
  await page.getByLabel("Tôi xác nhận thay đổi quyền sử dụng của công ty này.").check();
  await page.getByRole("button",{name:"Xác nhận",exact:true}).click();
  await expect(page.getByRole("row").filter({hasText:code})).toContainText("Tạm ngưng");
});
